### ISSUE TITLE
Blog post timestamp de-highlighted

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#150]
Currently blog roll has the timestamp with same emphasis as more important text.

![36E9D479-41D0-4F7B-BA76-30B998F4CA87](https://user-images.githubusercontent.com/49922/181489987-21f6dd81-9302-4e32-ad9a-b7e8ef58f002.png)

Maybe to de-emphasis this with grayed colour to improve readability.

**Comment by kenkunz** [comment]
Good catch!

I've updated it in my working branch to match what's in figma. It's somewhat subtle ("gray-dark" instead of "ink-light" color). Let me know if this looks good or if you'd like it further de-emphasized.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/35901/181580347-47088bac-e8d1-427a-9971-672e6a02c671.png">

**Comment by kenkunz** [comment]
@miohtama let me know if this can be closed. See below image for current style (matches figma). If you would still like a lighter color for timestamp, let's move this to `design-system` as a `P1` and assign to Alek.

**Comment by kenkunz** [comment]
This does not appear to be an issue anymore after various design system improvements were completed.
