### ISSUE TITLE
Not all trading data pages decide narrow layout

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#173]
Now it looks a bit funny, because the logo and the tables are not aligned on left and right.

- Most trading data pages would be better off with wide layout (due to lots of data)
- Only the 
    - trading data landing page
    - historical data page
    - API key registration form

... need narrow layout

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/49922/185595474-947ada7c-9dd7-4b56-a3c3-50c81a86c700.png">

**Comment by kenkunz** [comment]
@miohtama – quick clarification on which pages require narrow layout…

(adding numbers so you can reference these in your response)

**[1] Trading data landing page** – this one currently has narrow layout, but will actually switch to wide layout (per https://github.com/tradingstrategy-ai/design-system/issues/64)

**[2] Historical Data page** – I wasn't sure if you meant **(a)** [`trading-view/backtesting`](https://tradingstrategy.ai/trading-view/backtesting) or **(b)** the trading pair [API and historical data](https://tradingstrategy.ai/trading-view/ethereum/uniswap-v2/wise-eth/api-and-historical-data) page. (a) seems like it would benefit from the wider layout (more breathing-room for columns / headers).

**[3] API key registration form** – ✔️ got it (that one is obvious)

**[4] Blockchains** (shown in the screenshot above) – I would suggest we use a narrower layout for this page. If we use the wide layout, the columns will be very spread out and the explanatory text will be super wide (though we can increase the font size). Longer-term, a table is not the best UI for this page (unless you plan to add more columns) – perhaps change this to tiles?

**[5] all pages with a narrower layout** – I suggest we align the breadcrumbs to the nav-bar (full width) rather than to the narrower content column.

Thoughts?

**Comment by miohtama** [comment]
For 2) was about backtesting page with a lot of textual content

4)We can add more columns to fill the empty space - can you open a separate ticket on this, I have some ideas what we need to add (and what was originally missing)

5) Breadcrumbs definitely full width
