### ISSUE TITLE
Price label tweaking

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#18]
For price labels, there are good, but we might make them a bit more novice-friendly. Can you please try the following:

- "Up more than 5%"
- "Up"
- "Down"
- "Down more than 5%"

This is less technical and has per cent ranges tweaked a bit for the more volatile ranges of cryptos

<img width="207" alt="image" src="https://user-images.githubusercontent.com/49922/157933555-40b2704a-fd89-47b0-bcb4-26c025227a2a.png">
.

**Comment by kenkunz** [comment]
Makes sense.

What's your opinion of the "close to zero" option? Remove this or keep it? If keeping it, what should the threshold and label be?

**Comment by kenkunz** [comment]
@miohtama I wanted to confirm the desired behavior of "Up" and "Down" options.

Should "Up" include _all_ pairs with `price_change_24 > 0`, or only `0 < price_change_24 < 5%`?

My intuition is to go with the former – "Up" means "all up!". That said, this makes the behavior of the price change filter a little different than the others, as the filter ranges are overlapping instead of exclusive. So if you first select "Up" and then additionally check "Up > 5%", you won't see a change (you'd need to un-check "Up" to _only_ see those with price change > 5%).

We could consider making this a radio button set instead of checkboxes. It's a little more work b/c we can't reuse the existing `Filter.svelte` component.

My suggestion for now is to leave it as checkboxes and allow the overlapping filter ranges – I think people will figure it out.
