### ISSUE TITLE
Aave: Add Reserve details page

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#216]
**Epic:** tradingstrategy-ai/oracle#116

# Goal

Add a new `frontend` page that displays lending reserve details and borrow/supply charts.

## Details

- page route: `/trading-view/[chain]/lending/[protocol]/[reserve]`
- backend API: tbd (see tradingstrategy-ai/backend#66)
- follow UI patterns used for trading pair details (summary, description, borrow chart, supply chart - or maybe single chart with one set of candles and one line)
- remember to add this new page to `sitemap.xml`

**Comment by kenkunz** [comment]
In light of @plamut's comment here:
https://github.com/tradingstrategy-ai/frontend/issues/211#issuecomment-1422289940

I would like to better understand whether the intent of this ticket is to display a _protocol_ details (with list of _reserves_) or a _reserve_ details?

**Comment by plamut** [comment]
@kenkunz Who is this comment aimed at?

If at me, I cannot really say, unfortunately, as I derived the API tickets from the already existing frontend tickets.
At the moment, I am developing a `/reserve/details` endpoint, which will presumably return everything about a particular reserve that we know (mostly various trade stats and aggregations?).

In my (personal!) opinion, it's unlikely that we will have a `/protocol` API endpoint, because adding a new protocol requires new code, it wouldn't be just another DB record. If we have a protocol details page, I imagine a lot of the info would be hardcoded, mind the various trade stats and reserves listing.

Maybe a "protocol details page" is actually the same as a "reserve listing page", just with some extra hardcoded info? (e.g. a brief protocol description)

@miohtama Can you chime in?

**Comment by miohtama** [comment]
Update the structure to 

`/trading-view/polygon/lending/[protocol]/reserve]`

E.g.

`/trading-view/polygon/lending/aave-v3/usdc`

**Comment by kenkunz** [comment]
This is **blocked** by: tradingstrategy-ai/backend#142

**Comment by kenkunz** [comment]
@miohtama per your [comment above](https://github.com/tradingstrategy-ai/frontend/issues/216#issuecomment-1429375227), the breadcrumbs will look like:

> Trading data » Polygon » Lending protocols » Aave v3 » USDC

However, we won't (initially) have pages for the intermediate pages in the breadcrumbs ("Lending protocols" or "Aave v3").

How would you like to handle this? I can think of a couple options, in order of easiest to hardest:
1. add redirects at these routes that automatically send the user to the parent chain page (this could be surprising / unexpected user experience)
2. add placeholder pages with minimum content and a link to the parent chain page.
3. modify our `Breadcrumbs` component to check if a given path segment has a valid route
   - if yes, add a clickable crumb segment as usual
   - if no, add a non-clickable crumb segment (no hover style, default cursor)
 
Option 3 is not trivial – I can't find an easy way in SvelteKit to check if a route exists for a URL (this would be a nice enhancement). I may be able to hack this using Vite's `import.meta.glob`.
