### ISSUE TITLE
Trading pair page doesn't always show correct 'ticker' 

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/frontend#238]
Tickers are needed for creating strategies. For example, the correct ticker for the pair shown below is ```("wbnb","usdt")```, but a user could easily think the correct ticker is ```("bnb","usdt")``` or even ```("usdt","bnb")```, both of which don't work.

<img width="1440" alt="Screenshot 2022-11-16 at 21 31 56" src="https://user-images.githubusercontent.com/74208897/202277584-871515ce-a5f9-4a90-b873-75b7914b0213.png">

**Comment by kenkunz** [comment]
Thanks, @AlexTheLion123.

Looking at the data from `/api/pair-details`, it appears that the `pair_symbol` field uses the `friendly` versions of the token symbols. Here's a truncated API response with the relevant keys:

```json
{
  "summary": {
    "pair_id": 1364813,
    "pair_name": "Wrapped BNB-Tether USD",
    "pair_symbol": "BNB-USDT",
    "pair_slug": "bnb-usdt",
    "base_token_symbol": "WBNB",
    "base_token_symbol_friendly": "BNB",
    "quote_token_symbol": "USDT",
    "quote_token_symbol_friendly": "USDT"
  }
}
    
```

If we want to use the _non_-`friendly` symbols, I think we'd want to change this on the backend so that we are referencing a consistent `pair_symbol` everywhere.

@miohtama – can you comment on this? I'm guessing there's a reason we're using the `friendly` symbols in the `pair_symbol`. Thoughts on changing this … or some other way to address the concern raised by @AlexTheLion123?

**Comment by miohtama** [comment]
Waiting for strategy wizard feature that is on hold and pending Pyodide integration.

**Comment by kenkunz** [comment]
Per discussion at backlog meeting (and Mikko's comment above), closing this as "won't fix".
