### ISSUE TITLE
Typesense: export info as zero

### ISSUE THREAD

**Issue by plamut** [tradingstrategy-ai/frontend#287]
Background: https://github.com/tradingstrategy-ai/oracle/pull/214#issuecomment-1359056234

TypeSense data [has changed](https://github.com/tradingstrategy-ai/oracle/pull/214/files#diff-f7ac9b22dd34e5f93fc6a409ee8e9f0e05007b5c01da3a66f594bed2813dd74e) a bit - TradeEntity objects now have the `exchange_type` field (where applicable), and with that some of the exchanges are marked as `"uniswap_v2_incompatible"`. 

Those blacklisted exchanges with their own non-standard math should have their trade stats set to zero. Type sense should already export those as such, but please double check, just in case.

**Comment by kenkunz** [comment]
The Typesense search index data does not appear to be updated yet.

Example query: [BUSD-USDT Nomiswap](https://tradingstrategy.ai/search?q=BUSD-USDT+Nomiswap&sortBy=liquidity%3Adesc&filters=%7B%22price_change_24h%22%3A%5B%5D%2C%22liquidity%22%3A%5B%5D%2C%22volume_24h%22%3A%5B%5D%2C%22type%22%3A%5B%5D%2C%22blockchain%22%3A%5B%5D%2C%22exchange%22%3A%5B%5D%7D)

<img width="826" alt="image" src="https://user-images.githubusercontent.com/35901/209244284-7ebdd220-ba53-49b7-8300-0cbe147c2f2d.png">

**Comment by kenkunz** [comment]
After reviewing the original [issue](https://github.com/tradingstrategy-ai/oracle/issues/176) and [PR](https://github.com/tradingstrategy-ai/oracle/pull/214), I have a couple questions…

### 1. exclude `uniswap_v2_incompatible` entities from search results?

Is the intention to fully exclude `uniswap_v2_incompatible` entities from the search results?

Currently, once the search index records are updated with the numeric metrics set to `null` (`price_change_24h`, `volume_24h`, `liquidity`, `price_usd_latest`), the trading pairs will automatically be de-ranked in the search results since our default rank is based on `liquidity`.

If we want to _fully exclude_ them instead of just de-ranking them, there are a few options:
- **a.** exclude these records from the search index entirely (this makes sense if we _never_ want to include them in search results)
- **b.** add some additional special-case logic to the query criteria used by `frontend` when it queries the search index (don't love this option)
- **c.** push the business logic decision to the backend by introducing a different field to the search index, e.g., `exclude_from_search_results` (not sure what benefit this has over option a above)

My opinion FWIW: _don't_ fully exclude these entities from search results, just de-rank. I'm not _just_ saying this b/c it's the easiest option 😜. I think there may be scenarios where people want to find these entities.

### 2. mark these entities as _low quality_ in the search results?

If the answer to **1** above is "no" – i.e., we don't want to _fully exclude_ these entities – do we want to mark them as _low quality_?

We currently mark a search result hit as _low quality_ if the `liquidity` is below a certain threshold. _Low quality_ results include a warning indicator and have their opacity reduced. Here's an [example query](http://localhost:5173/search?q=elon&sortBy=price_change%3Aasc&filters=%7B%22price_change_24h%22%3A%5B%5D%2C%22liquidity%22%3A%5B%22500000-0%22%5D%2C%22volume_24h%22%3A%5B%5D%2C%22type%22%3A%5B%5D%2C%22blockchain%22%3A%5B%5D%2C%22exchange%22%3A%5B%5D%7D) with _low quality_ results (see screenshot below).

Since these entities will have their `liquidity` set to `null` or `0`, they will (currently) automatically be flagged as _low quality_. If we _don't_ want to mark them as such, then the [`quality_factors` field in the search index](https://github.com/tradingstrategy-ai/search/blob/main/docs/trading-entities.md) should _not_ include the value `liquidity`.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/35901/209246038-b6170a79-e8a4-4c63-87d2-35676bf7e71f.png">

**Comment by kenkunz** [comment]
@miohtama can you comment on the two questions above?

**#⁠1** – if we just want them _de-ranked_ then this is already the desired behavior (based on the default `liquidity:desc` rank).

**#⁠2** – currently these pairs are _not_ being flagged as _low quality_. This is because the `typesense` API does not include any value for optional fields left blank, and `undefined < LIQUIDITY_QUALITY_THRESHOLD` is `false` in JavaScript. It's an easy change we want to flag them as _low quality_ – just need to know the preference here.

**Comment by miohtama** [comment]
#1: Hopeful fix:

Uni v3 -> not de-ranked even though no liquidity
Other types -> deranked 

#2: Low quality

If type is not supported flag as low quality.

**Comment by miohtama** [comment]
Potential ranking formula

- rank = (type == uni_v3) * 10_000_000 + liquiditity   

(Boost uni v3 pairs with assumed $10M liquidity)
