### ISSUE TITLE
Uniswap v3 listing quick fixes

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/frontend#297]
There are multiple pairs and columns with bad data

- Remove liquidity column until we have data
- Add fee % column
- Check other lists that could have the same issue above

https://tradingstrategy.ai/trading-view/ethereum/uniswap-v3

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/49922/210512351-aa4f57ee-4ac4-4828-acaa-48f16799dde1.png">

**Comment by kenkunz** [comment]
## Audit of pages with trading pair liquidity

The following pages on our site include pair liquidity data:

| #   | Page | Route | Notes |
| --- | ---- | ----- | ----- |
| **1.** | **Blockchain details page** |`/trading-view/[chain]` | pairs table (bottom) includes `usd_liquidity_latest` |
| **2.** | **Trading pairs index page** | `/trading-view/trading-pairs` | includes `usd_liquidity_latest` and `liquidity_change_24h` |
| **3.** | **Token details page** | `/trading-view/[chain]/tokens/[token]` | pairs table includes `usd_liquidity_latest` and `liquidity_change_24h` |
| **4.** | **Exchange details page** | `/trading-view/[chain]/[exchange]` | includes `usd_liquidity_latest` and `liquidity_change_24h` |
| **5.** | **Trading pair details page** | `/trading-view/[chain]/[exchange]/[pair]` | pair info table and summary description include `usd_liquidity_latest` |

**Comment by kenkunz** [comment]
## Suggested API change

Currently, the `/pairs` endpoint (and others) return `0` values for various liquidity metrics for Uniswap V3 pairs (including       `usd_liquidity_latest`, `liquidity_change_24h`, `usd_liquidity_change_24h`). Also, the `liquidity_type` is `xyliquidity`, making it harder to distinguish these pairs from traditional Uniswap V2 style pairs (without looking specifically at the `exchange_type`).

### Proposal:
- return `null` instead of `0` for the liquidity metrics listed above
- return `concentrated-liquidity` instead of `xyliquidity` for `liquidity_type`

This would make it easier to implement the requested `frontend` changes without needing to apply "special case" logic for Uniswap V3 – would could create additional maintenance burden as we add additional exchanges with concentrated liquidity in the future.

**Comment by miohtama** [comment]
1. Keep liquidity columns 
2. Add fee as well
3. For Uni v3 only pairs page -> different columns preferred

**Comment by miohtama** [comment]
Let's call the new type `uniswap-v3-style-concentrated-liquidity`
