### ISSUE TITLE
Update strategy position pair ticker to support new options

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/frontend#646]
# Goal

As an investor viewing a strategy position, I want a clear, concise description about the assents and type of position to be displayed, so that I can readily understand the trading activity associated with a strategy.

## Background

As of `2023-12-18`, our first strategy with support for short positions is live ("ETH mean reversion bounce"). The position data supplied by `trade-executor` has been enriched to include additional information about the traded assets and type of position.

See: [trade-executor:identifier.py](https://github.com/tradingstrategy-ai/trade-executor/blob/a800c9f9800467c48e0e52518bab26354279add5/tradeexecutor/state/identifier.py)

## Details

| kind | Description | Ticker symbol source | Suffix | Full pair ticker |
| --- | --- | --- | --- | --- |
| spot_market_hold or `null` | Simple trade on a DEX | The pair's `base` and `quote` tokens | spot | WETH&#x2011;USDC&#160;spot |
| lending_protocol_short | A short position using Aave (or similar) lending reserve | The `underlying_spot_pair`'s `base` and `quote` tokens | short | WETH&#x2011;USDC&#160;short |
| lending_protocol_long | A long position using Aave (or similar) lending reserve | The `underlying_spot_pair`'s `base` and `quote` tokens | long | WETH&#x2011;USDC&#160;long |
| credit_supply | Supplying credit to Aave lending reserve | The pair's `quote` token | credit | USDC&#160;credit |

## Open questions

1. What is the correct source of the token symbol for a `credit_supply` position?
   - **A:** quote token [(see below)](#issuecomment-1862220445)
3. Do we need a ticker format option for `spot_market_hold_rebalancing_token` positions?
   - **A:** no [(see below)](#issuecomment-1862220445)

## Acceptance criteria

1. Position ticker includes the correct token symbols and suffix as defined in the table above
2. Position ticker is displayed for each position open / closed / frozen positions tables
5. Position ticker is displayed on position details page

**Comment by miohtama** [comment]
1. In credit supply (we do not have any live executed yet) the name is `pair.quote.token_symbol + “ credit”`
2. `spot_market_hold_rebalancing_token` can be ignored for now, as we do not have any such tokens yet (would be like `stETH` or other liquid rebalancing tokens)

**Comment by miohtama** [comment]
We also need to have buy/sell verbs for the individual trades as the following

Spot
- Open position -> Buy XXX 
- Close position -> Sell XXX

Short 
- Open position -> Sell YYY
- Close position -> BuyYYY

This should be defined as following: If `TradeExecution.executed_quantity < 0` then “Sell” otherwise “Buy” and is true for spot, short and long (but not credit).

Also there is new `TradeExecution.flags` set that can contain the following flags (only for new data):
`[“open”, “close”, “increase”, “reduce”, “test_trade”]`. Open + increase and close + reduce are always set at the same time. For spot, `increase` means that the position was already open and there was additional buy (exposure increased). For short `increase` means that the position was already open and there was additioanl sell (exposure increase).
